=== LucasAlfare/calcubetimer/cct/trunk/guiLayouts/layout.dtd
<!ELEMENT gui (panel,menubar)?>

<!ELEMENT panel (center,north,south,east,west,page_start,page_end,line_start,line_end,(splitpane,component,button,checkbox,label,selectablelabel)*)?>
<!ELEMENT center (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT north (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT south (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT east (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT west (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT page_start (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT page_end (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT line_start (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ELEMENT line_end (panel|splitpane|component|button|checkbox|label|selectablelabel)?>

<!ELEMENT menubar (menu|glue|component|button|checkbox|label|selectablelabel)*>
<!ELEMENT menu (#PCDATA|menuitem|separator|checkboxmenuitem|component)*>

<!ELEMENT scrollpane (panel|splitpane|component|button|checkbox|label|selectablelabel)?>
<!ATTLIST scrollpane verticalpolicy (always|never|asneeded) #IMPLIED>
<!ATTLIST scrollpane horizontalpolicy (always|never|asneeded) #IMPLIED>

<!ELEMENT splitpane (panel|component|button|checkbox|label|selectablelabel)*>
<!ATTLIST splitpane drawcontinuous (true|false) #IMPLIED>
<!ATTLIST splitpane resizeweight CDATA #IMPLIED>
<!ATTLIST splitpane split (horizontal|vertical) #IMPLIED>

<!ELEMENT component EMPTY>
<!ELEMENT separator EMPTY>
<!ELEMENT glue EMPTY>
<!ELEMENT button (#PCDATA)>
<!ELEMENT checkbox (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT selectablelabel (#PCDATA)>
<!ELEMENT menuitem (#PCDATA)>
<!ELEMENT checkboxmenuitem (#PCDATA)>
<!ELEMENT splitpane EMPTY>

<!ATTLIST panel layout (border|box|grid|flow) #IMPLIED>
<!ATTLIST panel orientation (horizontal|vertical|page|line) #IMPLIED>
<!ATTLIST panel hgap CDATA #IMPLIED>
<!ATTLIST panel vgap CDATA #IMPLIED>
<!ATTLIST panel rows CDATA #IMPLIED>
<!ATTLIST panel cols CDATA #IMPLIED>
<!ATTLIST panel align (left|right|center|leading|trailing) #IMPLIED>

<!ATTLIST component type CDATA #REQUIRED>

<!ATTLIST button action CDATA #IMPLIED>
<!ATTLIST checkbox action CDATA #IMPLIED>
<!ATTLIST menuitem action CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem action CDATA #IMPLIED>

<!ATTLIST panel alignmentX CDATA #IMPLIED>
<!ATTLIST component alignmentX CDATA #IMPLIED>
<!ATTLIST button alignmentX CDATA #IMPLIED>
<!ATTLIST checkbox alignmentX CDATA #IMPLIED>
<!ATTLIST menuitem alignmentX CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem alignmentX CDATA #IMPLIED>

<!ATTLIST panel alignmentY CDATA #IMPLIED>
<!ATTLIST component alignmentY CDATA #IMPLIED>
<!ATTLIST button alignmentY CDATA #IMPLIED>
<!ATTLIST checkbox alignmentY CDATA #IMPLIED>
<!ATTLIST menuitem alignmentY CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem alignmentY CDATA #IMPLIED>

<!ATTLIST component border CDATA #IMPLIED>
<!ATTLIST button border CDATA #IMPLIED>
<!ATTLIST checkbox border CDATA #IMPLIED>
<!ATTLIST menuitem border CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem border CDATA #IMPLIED>

<!ATTLIST component opaque CDATA #IMPLIED>
<!ATTLIST button opaque CDATA #IMPLIED>
<!ATTLIST checkbox opaque CDATA #IMPLIED>
<!ATTLIST menuitem opaque CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem opaque CDATA #IMPLIED>

<!ATTLIST component background CDATA #IMPLIED>
<!ATTLIST button background CDATA #IMPLIED>
<!ATTLIST checkbox background CDATA #IMPLIED>
<!ATTLIST menuitem background CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem background CDATA #IMPLIED>

<!ATTLIST component foreground CDATA #IMPLIED>
<!ATTLIST button foreground CDATA #IMPLIED>
<!ATTLIST checkbox foreground CDATA #IMPLIED>
<!ATTLIST menuitem foreground CDATA #IMPLIED>
<!ATTLIST checkboxmenuitem foreground CDATA #IMPLIED>

<!ATTLIST selectablelabel editable (true|false) #IMPLIED>

<!ATTLIST menu mnemonic CDATA #IMPLIED>
<!ATTLIST glue orientation (horizontal|vertical) #IMPLIED>
<!ATTLIST separator orientation (horizontal|vertical) #IMPLIED>

=== LucasAlfare/calcubetimer/cct/trunk/guiLayouts/jnetcube.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
		<splitpane drawcontinuous="true" resizeweight=".8" split="horizontal">
			<panel layout="border">
				<center>
					<panel layout="box" orientation="page">
						<panel layout="box" orientation="horizontal">
							<panel layout="box" orientation="page">
								<component type="scrambleChooser"/>
								<component alignmentX=".5" type="stackmatStatusLabel"/>
								<panel> <!-- This is to prevent the grid layout from getting squished -->
									<panel layout="grid" cols="2">
										<label>Scramble length:</label>
										<component type="scrambleLength" />
										<label>Scramble number: </label>
										<component type="scrambleNumber"/>
									</panel>
								</panel>
								<component type="scrambleAttributes"/>
							</panel>
							<panel layout="box" orientation="page" preferredsize="500x100">
								<component border="Use this algorithm to scramble your cube;000000" type="scrambleText"/>
							</panel>
						</panel>
						<component type="timerDisplay"/>
					</panel>
				</center>
				<south>
					<panel layout="box" orientation="page">
						<panel layout="box" orientation="line">
							<panel layout="border" border="Session Statistics">
								<center>
									<panel layout="box" orientation="page">
										<label>Recent Time: $$currentTime$$</label>
										<label>Previous Time: $$lastTime$$</label>
										<label>Progress: $$progressTime$$ seconds</label>
										<panel preferredsize="10x15"></panel>
										<label>Cubes Solved: $$solves$$</label>
										<label>Session Average: $$sessionAverage$$ seconds</label>
									</panel>
								</center>
								<line_end>
									<panel layout="box" orientation="page">
										<button action="sessionAverage">Detail</button>
										<button action="addTime">Add Time</button>
										<button action="reset">Reset</button>
									</panel>
								</line_end>
							</panel>
							<panel layout="border" border="Rolling Average">
								<panel layout="box" orientation="page">
									<label>Current Average: $$currentAverage$$</label>
									<label>Progress: $$progressAverage0$$</label>
									<panel preferredsize="10x15"></panel>
									<label>Fastest Time: $$bestTimeOfCurrentAverage0$$</label>
									<label>Slowest Time: $$worstTimeOfCurrentAverage0$$</label>
									<label>Standard Deviation: $$currentSD$$</label>
								</panel>
							</panel>
						</panel>
						<panel border="Best Average" layout="box" orientation="page">
							<button action="bestAverage0" alignmentX=".99">Details</button>
							<selectablelabel border=";000000" alignmentX=".99">
								<![CDATA[<html>Average: $$bestRA0$$<br/>Individual Times: $$bestAverageList0$$</html>]]>
							</selectablelabel>
						</panel>
					</panel>
				</south>
			</panel>
			<panel nominsize="false" layout="border">
				<tabbedpane>
					<component name="Times" type="timesList"/>
					<component name="Sessions" type="sessionsList"/>
				</tabbedpane>
			</panel>
		</splitpane>
	</panel>
	<menubar>
		<menu mnemonic="f">File
			<menuitem action="bestAverage0">Save Best Average As</menuitem>
			<menuitem action="sessionAverage">Save Session Average As</menuitem>
			<separator/>
			<menuitem action="showConfiguration">Options...</menuitem>
			<separator/>
			<menuitem action="exit">Exit</menuitem>
		</menu>
		<menu mnemonic="t">Tools
			<menuitem action="importScrambles">Import Scrambles</menuitem>
			<menuitem action="exportScrambles">Scramble Generator</menuitem>
			<checkboxmenuitem action="togglescramblepopup">View Scramble</checkboxmenuitem>
		</menu>
		<menu mnemonic="o">CCT Options
			<component type="customGUIMenu"/>
			<menu mnemonic="k">Keyboard Timer
				<checkboxmenuitem action="toggleLessAnnoyingDisplay">Use less-annoying status light</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">Hide scrambles when timer not focused</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">Only spacebar starts timer</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">Fullscreen while timing</checkboxmenuitem>
			</menu>
		</menu>
		<menu>Network Timer
			<menuitem action="connectToServer">Connect to server</menuitem>
		</menu>
		<menu mnemonic="h">Help
			<menuitem action="showAbout">About</menuitem>
		</menu>
		<glue orientation="horizontal"/>
		<component type="profilecombobox"/>
		<button nominsize="true" action="togglefullscreen"/>
	</menubar>
</gui>

=== LucasAlfare/calcubetimer/cct/trunk/guiLayouts/cct.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gui SYSTEM "layout.dtd">
<gui>
	<panel layout="border">
		<splitpane drawcontinuous="true" resizeweight=".7" split="horizontal">
			<panel layout="border">
				<center>
					<panel layout="box" orientation="page">
						<component type="timerDisplay"/>
						<component type="scrambleArea"/>
					</panel>
				</center>
				<south>
					<panel layout="box" orientation="page">
						<scrollpane verticalpolicy="never" horizontalpolicy="asneeded">
							<panel alignmentY=".5" layout="flow" hgap="5" vgap="5">
								<component type="stackmatStatusLabel"/>
								<component type="scrambleChooser"/>
								<component type="scrambleLength"/>
								<component type="scrambleNumber"/>
								<component type="scrambleAttributes"/>
							</panel>
						</scrollpane>
						<panel layout="border">
							<line_start><button action="submitSundayContest">%%submitsunday%%</button></line_start>
							<center><panel><checkbox alignmentX=".5" action="keyboardTiming">%%usekeyboard%%</checkbox></panel></center>
							<line_end>
								<panel>
									<button action="newSession">%%newsession%%</button>
									<button action="reset">%%clearsession%%</button>
								</panel>
							</line_end>
						</panel>
						<panel layout="box" orientation="line">
							<panel border="%%seshstats%%" layout="grid" cols="1">
								<panel layout="box" orientation="line">
									<label>%%raof%% $$RASize0$$</label>
									<button action="currentAverage0"><![CDATA[<html><font color="$$configuration_Statistics_Color_currentAverage$$">%%currave%% $$currentAverage0$$ $$progressAverageParens0$$</font></html>]]></button>
									<button action="bestAverage0"><![CDATA[<html><font color="$$configuration_Statistics_Color_bestRA$$">%%bestra%% $$bestRA0$$</font></html>]]></button>
								</panel>
								<panel layout="box" orientation="line">
									<label>%%raof%% $$RASize1$$</label>
									<button action="currentAverage1"><![CDATA[<html><font color="$$configuration_Statistics_Color_currentAverage$$">%%currave%% $$currentAverage1$$ $$progressAverageParens1$$</font></font></html>]]></button>
									<button action="bestAverage1"><![CDATA[<html><font color="$$configuration_Statistics_Color_bestRA$$">%%bestra%% $$bestRA1$$</font></html>]]></button>
								</panel>
								<panel layout="box" orientation="line">
									<label>$$solves$$/$$attempts$$ (%%solves%%/%%attempts%%)</label>
									<button action="sessionAverage"><![CDATA[<html>%%seshave%% $$sessionAverage$$ $$progressSessionAverageParens$$</html>]]></button>
								</panel>
							</panel>
							<panel border="%%history%%" layout="box" orientation="page">
								<panel><label alignmentX=".5">%%bestever%% $$veryBestTime$$</label></panel>
								<panel><label alignmentX=".5">%%bestraof%% $$RASize0$$: $$veryBestRA0$$</label></panel>
								<panel><label alignmentX=".5">$$globalSolveCount$$/$$globalAttemptCount$$ %%globalaverage%% $$globalAverage$$</label></panel>
							</panel>
						</panel>
					</panel>
				</south>
			</panel>
			<panel nominsize="false" layout="border">
				<tabbedpane>
					<component name="%%times%%" type="timesList"/>
					<component name="%%sessions%%" type="sessionsList"/>
				</tabbedpane>
			</panel>
		</splitpane>
	</panel>
	<menubar>
		<menu mnemonic="f">%%file%%
			<menuitem action="importScrambles">%%import%%</menuitem>
			<menuitem action="exportScrambles">%%export%%</menuitem>
			<separator/>
			<menuitem action="addTime">%%addtime%%</menuitem>
			<separator/>
			<menuitem action="connectToServer">%%connect%%</menuitem>
			<separator/>
			<menuitem action="showConfiguration">%%configuration%%</menuitem>
			<separator/>
			<menuitem action="exit">%%exit%%</menuitem>
		</menu>
		<menu mnemonic="o">%%options%%
			<menuitem action="undo"/>
			<menuitem action="redo"/>
			<separator/>
			<checkboxmenuitem action="toggleScramblePopup">%%togglescramblepopup%%</checkboxmenuitem>
			<menu mnemonic="k">%%keyboardtimer%%
				<checkboxmenuitem action="toggleLessAnnoyingDisplay">%%lessannoying%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleHideScrambles">%%hidescrambles%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleSpacebarStartsTimer">%%spacebaronly%%</checkboxmenuitem>
				<checkboxmenuitem action="toggleFullscreenTiming">%%fullscreentiming%%</checkboxmenuitem>
			</menu>
			<component type="customGUIMenu"/>
		</menu>
		<glue orientation="horizontal"/>
		<button nominsize="true" action="undo"/>
		<button nominsize="true" action="redo"/>
		<component type="languagecombobox"/>
		<component type="profilecombobox"/>
		<glue orientation="horizontal"/>
		<menu mnemonic="h">%%help%%
			<menuitem action="showDocumentation">%%documentation%%</menuitem>
			<menuitem action="showAbout">%%about%%</menuitem>
		</menu>
		<button nominsize="true" action="togglefullscreen">+</button>
	</menubar>
</gui>
